# WhatsApp Userbot Configuration
bot:
  name: "AdvancedUserBot"
  version: "2.0.0"
  debug: true
  auto_start: true
  session_timeout: 3600  # 1 hour

whatsapp:
  auth_method: "qr"  # qr or phone
  phone_number: ""  # Optional: +1234567890
  session_dir: "./sessions"
  headless: false
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  implicit_wait: 10
  page_load_timeout: 30
  
telegram:
  enabled: true
  bot_token: ""  # Your Telegram bot token
  bridge_group_id: ""  # Telegram group ID for bridging
  admin_users: []  # List of Telegram user IDs who can manage
  thread_per_user: true
  forward_media: true
  max_message_length: 4096

database:
  type: "mongodb"  # mongodb or local
  mongodb:
    connection_string: ""  # MongoDB connection string
    database_name: "whatsapp_userbot"
    collections:
      messages: "messages"
      users: "users"
      sessions: "sessions"
      modules: "modules"
  local:
    db_file: "./data/userbot.db"

modules:
  auto_load: true
  system_modules_dir: "./modules/system"
  custom_modules_dir: "./modules/custom"
  enabled_modules: []

logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "./logs/userbot.log"
  max_size: "10MB"
  backup_count: 5
  console_output: true

security:
  rate_limit: 30  # messages per minute
  blacklist: []
  whitelist: []
  admin_only_commands: true