# WhatsApp Userbot Configuration
bot:
  name: "AdvancedUserBot"
  version: "2.0.0"
  debug: true
  auto_start: true
  session_timeout: 3600
whatsapp:
  auth_method: "qr"
  phone_number: "+923298784489"
  session_dir: "/app/sessions"
  headless: true
  user_agent: "Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.7151.119 Safari/537.36"
  implicit_wait: 10
  page_load_timeout: 60
webdriver:
  chrome_binary: "/usr/bin/chromium-browser"
  driver_path: "/usr/bin/chromium-chromedriver"
  headless: true
telegram:
  enabled: true
  bot_token: "7580382614:AAH30PW6TFmgRzbC7HUXIHQ35GpndbJOIEI"
  bridge_group_id: "-1002287300661"
  admin_users: [7405203657]
  thread_per_user: true
  forward_media: true
  max_message_length: 4096
database:
  type: "mongodb"
  mongodb:
    connection_string: "mongodb+srv://irexanon:xUf7PCf9cvMHy8g6@rexdb.d9rwo.mongodb.net/?retryWrites=true&w=majority&appName=RexDB"
    database_name: "whatsapp_userbot"
    collections:
      messages: "messages"
      users: "users"
      sessions: "sessions"
      modules: "modules"
  local:
    db_file: "./data/userbot.db"
modules:
  auto_load: true
  system_modules_dir: "./modules/system"
  custom_modules_dir: "./modules/custom"
  enabled_modules: []
logging:
  level: "INFO"
  file: "./logs/userbot.log"
  max_size: "10MB"
  backup_count: 5
  console_output: true
security:
  rate_limit: 30
  blacklist: []
  whitelist: []
  admin_only_commands: true
